version: '3.8'

services:
  # Development Frontend with Hot Reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    command: npm run dev
    networks:
      - treasury-dev-network

  # Development Database
  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: treasury_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - treasury-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - treasury-dev-network

volumes:
  postgres-dev-data:

networks:
  treasury-dev-network:
    driver: bridge