version: '3.8'

services:
  # Development Frontend with Hot Reload
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend-dev:3001
    command: npm run dev
    networks:
      - treasury-dev-network
    depends_on:
      - backend-dev

  # Development Backend API
  backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://NiobiFintechAssessment:NiobiFintechAssessment@niobifintechassessment.1uep0g9.mongodb.net/?retryWrites=true&w=majority
    command: npm run dev
    networks:
      - treasury-dev-network

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - treasury-dev-network

networks:
  treasury-dev-network:
    driver: bridge